services:
  db:
    image: postgres:16
    container_name: smartrisk_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartrisk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - smartrisk_pgdata:/var/lib/postgresql/data

volumes:
  smartrisk_pgdata:
